import { createHmac, timingSafeEqual } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Readable } from "node:stream";

import { env } from "./env";

/**
 * Object storage.
 *
 * Two drivers, chosen by configuration:
 *
 *   local  writes under STORAGE_ROOT, serves through /api/files with an
 *          HMAC-signed, expiring URL. What makes the app runnable without a
 *          cloud account. Useless on a serverless host, where the filesystem is
 *          read-only or discarded between requests.
 *
 *   s3     Any S3-compatible object store: Cloudflare R2, Supabase Storage.
 *          Presigned GETs come straight from the store, so photographs never
 *          transit our server and never touch its egress bill. R2 is the better
 *          choice past ~200GB because it charges no egress at all; Supabase
 *          Storage is the simpler one when the database is already there.
 *
 * Both hand out URLs that stop working. That is the property the product needs:
 * without an expiry, one shared link becomes permanent public access to a
 * photograph of somebody, which is how "the whole album leaked" usually happens
 * in this category.
 */

export interface StorageDriver {
  readonly kind: "local" | "s3";
  put(bucket: string, key: string, body: Uint8Array, contentType?: string): Promise<void>;
  delete(bucket: string, key: string): Promise<void>;
  exists(bucket: string, key: string): Promise<boolean>;
  /** For zip streaming. Node stream on both drivers. */
  getStream(bucket: string, key: string): Promise<Readable>;
  /** A URL that expires. Async because presigning R2 is. */
  signedUrl(bucket: string, key: string, ttlSeconds?: number): Promise<string>;
}

/**
 * Keys are generated by us, never supplied by a client — but this is the last
 * thing between a request and the filesystem, so it validates rather than
 * assumes.
 */
export function assertSafeKey(key: string): void {
  if (
    key.length === 0 ||
    key.length > 512 ||
    key.startsWith("/") ||
    key.includes("..") ||
    key.includes("\0") ||
    !/^[A-Za-z0-9._\-/]+$/.test(key)
  ) {
    throw new Error(`unsafe storage key: ${JSON.stringify(key)}`);
  }
}

export function assertSafeBucket(bucket: string): void {
  if (!/^[a-z0-9-]{1,64}$/.test(bucket)) {
    throw new Error(`unsafe bucket: ${JSON.stringify(bucket)}`);
  }
}

// ---------------------------------------------------------------------------
// Local signing
// ---------------------------------------------------------------------------

export function signaturePayload(bucket: string, key: string, expires: number): string {
  return `${bucket}\n${key}\n${expires}`;
}

export function signKey(bucket: string, key: string, expires: number): string {
  return createHmac("sha256", env.secret)
    .update(signaturePayload(bucket, key, expires))
    .digest("base64url");
}

export function verifySignature(
  bucket: string,
  key: string,
  expires: number,
  signature: string,
): boolean {
  if (!Number.isFinite(expires) || expires * 1000 < Date.now()) return false;

  const expected = Buffer.from(signKey(bucket, key, expires));
  const given = Buffer.from(signature);
  // Length first: timingSafeEqual throws on a mismatch, and length is not secret.
  if (expected.length !== given.length) return false;
  return timingSafeEqual(expected, given);
}

// ---------------------------------------------------------------------------
// Local driver
// ---------------------------------------------------------------------------

export class LocalStorage implements StorageDriver {
  readonly kind = "local" as const;
  private readonly root: string;

  constructor(root: string) {
    this.root = root;
  }

  path(bucket: string, key: string): string {
    assertSafeBucket(bucket);
    assertSafeKey(key);
    const base = path.resolve(this.root, bucket);
    const full = path.resolve(base, key);
    // Re-check after resolving. Defence in depth is cheap and the failure mode
    // is serving arbitrary files off the disk.
    if (full !== base && !full.startsWith(base + path.sep)) {
      throw new Error("storage key escaped its bucket");
    }
    return full;
  }

  async put(bucket: string, key: string, body: Uint8Array) {
    const full = this.path(bucket, key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, body);
  }

  async delete(bucket: string, key: string) {
    await rm(this.path(bucket, key), { force: true });
  }

  async exists(bucket: string, key: string) {
    try {
      await stat(this.path(bucket, key));
      return true;
    } catch {
      return false;
    }
  }

  async getStream(bucket: string, key: string): Promise<Readable> {
    return createReadStream(this.path(bucket, key));
  }

  async signedUrl(bucket: string, key: string, ttlSeconds = env.signedUrlTtlSeconds) {
    assertSafeBucket(bucket);
    assertSafeKey(key);
    const expires = Math.floor(Date.now() / 1000) + ttlSeconds;
    return `/api/files/${bucket}/${key}?exp=${expires}&sig=${signKey(bucket, key, expires)}`;
  }
}

// ---------------------------------------------------------------------------
// R2 driver
// ---------------------------------------------------------------------------

export class S3Storage implements StorageDriver {
  readonly kind = "s3" as const;
  private client: import("@aws-sdk/client-s3").S3Client | null = null;

  /**
   * Constructed lazily. The SDK is a large import and most requests never touch
   * storage; more importantly, importing it at module scope would drag it into
   * every route's build-time evaluation.
   */
  private async s3() {
    if (!this.client) {
      const { S3Client } = await import("@aws-sdk/client-s3");
      this.client = new S3Client({
        // R2 has no regions and wants the literal "auto"; Supabase Storage
        // wants the project's real region and rejects "auto" in the signature.
        region: env.s3Region,
        endpoint: env.s3Endpoint,
        credentials: {
          accessKeyId: env.s3AccessKeyId,
          secretAccessKey: env.s3SecretAccessKey,
        },
        // Supabase Storage's S3 endpoint addresses buckets by path, not by
        // subdomain. R2 accepts either.
        forcePathStyle: true,
      });
    }
    return this.client;
  }

  async put(bucket: string, key: string, body: Uint8Array, contentType?: string) {
    assertSafeBucket(bucket);
    assertSafeKey(key);
    const { PutObjectCommand } = await import("@aws-sdk/client-s3");
    await (await this.s3()).send(
      new PutObjectCommand({
        Bucket: env.s3Bucket,
        Key: `${bucket}/${key}`,
        Body: body,
        ...(contentType ? { ContentType: contentType } : {}),
      }),
    );
  }

  async delete(bucket: string, key: string) {
    const { DeleteObjectCommand } = await import("@aws-sdk/client-s3");
    await (await this.s3()).send(
      new DeleteObjectCommand({ Bucket: env.s3Bucket, Key: `${bucket}/${key}` }),
    );
  }

  async exists(bucket: string, key: string) {
    const { HeadObjectCommand } = await import("@aws-sdk/client-s3");
    try {
      await (await this.s3()).send(
        new HeadObjectCommand({ Bucket: env.s3Bucket, Key: `${bucket}/${key}` }),
      );
      return true;
    } catch {
      return false;
    }
  }

  async getStream(bucket: string, key: string): Promise<Readable> {
    const { GetObjectCommand } = await import("@aws-sdk/client-s3");
    const result = await (await this.s3()).send(
      new GetObjectCommand({ Bucket: env.s3Bucket, Key: `${bucket}/${key}` }),
    );
    if (!result.Body) throw new Error(`${bucket}/${key} has no body`);
    return result.Body as Readable;
  }

  async signedUrl(bucket: string, key: string, ttlSeconds = env.signedUrlTtlSeconds) {
    assertSafeBucket(bucket);
    assertSafeKey(key);
    const { GetObjectCommand } = await import("@aws-sdk/client-s3");
    const { getSignedUrl } = await import("@aws-sdk/s3-request-presigner");
    return getSignedUrl(
      await this.s3(),
      new GetObjectCommand({ Bucket: env.s3Bucket, Key: `${bucket}/${key}` }),
      { expiresIn: ttlSeconds },
    );
  }
}

// ---------------------------------------------------------------------------

export const BUCKET = "event-photos";

let driver: StorageDriver | null = null;

/**
 * The configured driver.
 *
 * S3 whenever it is fully configured, local otherwise. Deliberately not
 * "whichever the operator asked for": a half-configured bucket that silently
 * falls back to a local filesystem on a serverless host is the failure that
 * loses photographs without erroring, so `env.s3Configured` requires every
 * value or none.
 */
export function storage(): StorageDriver {
  driver ??= env.s3Configured ? new S3Storage() : new LocalStorage(env.storageRoot);
  return driver;
}

/** Test seam: forget the cached driver after changing the environment. */
export function resetStorageForTests(): void {
  driver = null;
}

/** Only meaningful for the local driver; used by the /api/files route. */
export function localPath(bucket: string, key: string): string {
  const active = storage();
  if (!(active instanceof LocalStorage)) {
    throw new Error("localPath is only valid for the local storage driver");
  }
  return active.path(bucket, key);
}
