import { createHmac, timingSafeEqual } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import { env } from "./env";

/**
 * Object storage.
 *
 * The local driver writes under STORAGE_ROOT and is what makes the app runnable
 * without standing up Supabase Storage or an R2 bucket. Swapping in either is a
 * matter of implementing this interface — the rest of the app only knows about
 * bucket/key pairs and short-lived signed URLs, which is the shape all three
 * back ends share.
 *
 * Nothing outside this module joins a bucket and a key into a path. That is
 * what keeps a request for `../../etc/passwd` from becoming a file read.
 */

export interface StorageDriver {
  put(bucket: string, key: string, body: Buffer | Uint8Array): Promise<void>;
  delete(bucket: string, key: string): Promise<void>;
  exists(bucket: string, key: string): Promise<boolean>;
  /** A URL that stops working. Attendees never get a durable link to a photo. */
  signedUrl(bucket: string, key: string, ttlSeconds?: number): string;
}

/**
 * Keys are generated by us, never supplied by a client — but this is the last
 * line before the filesystem, so it validates rather than assumes.
 */
export function assertSafeKey(key: string): void {
  if (
    key.length === 0 ||
    key.length > 512 ||
    key.startsWith("/") ||
    key.includes("..") ||
    key.includes("\0") ||
    !/^[A-Za-z0-9._\-/]+$/.test(key)
  ) {
    throw new Error(`unsafe storage key: ${JSON.stringify(key)}`);
  }
}

export function assertSafeBucket(bucket: string): void {
  if (!/^[a-z0-9-]{1,64}$/.test(bucket)) {
    throw new Error(`unsafe bucket: ${JSON.stringify(bucket)}`);
  }
}

export function signaturePayload(
  bucket: string,
  key: string,
  expires: number,
): string {
  return `${bucket}\n${key}\n${expires}`;
}

export function signKey(bucket: string, key: string, expires: number): string {
  return createHmac("sha256", env.secret)
    .update(signaturePayload(bucket, key, expires))
    .digest("base64url");
}

export function verifySignature(
  bucket: string,
  key: string,
  expires: number,
  signature: string,
): boolean {
  if (!Number.isFinite(expires) || expires * 1000 < Date.now()) return false;

  const expected = Buffer.from(signKey(bucket, key, expires));
  const given = Buffer.from(signature);
  // Length check first: timingSafeEqual throws on a mismatch rather than
  // returning false, and the length is not a secret.
  if (expected.length !== given.length) return false;
  return timingSafeEqual(expected, given);
}

class LocalStorage implements StorageDriver {
  // A plain field rather than a constructor parameter property: `node --test
  // --experimental-strip-types` cannot strip those, and these modules are
  // exercised directly by the unit tests.
  private readonly root: string;

  constructor(root: string) {
    this.root = root;
  }

  private resolve(bucket: string, key: string): string {
    assertSafeBucket(bucket);
    assertSafeKey(key);
    const full = path.resolve(this.root, bucket, key);
    const base = path.resolve(this.root, bucket);
    // Even with the key validated, resolve and re-check: defence in depth is
    // cheap here and the failure mode is serving arbitrary files.
    if (full !== base && !full.startsWith(base + path.sep)) {
      throw new Error("storage key escaped its bucket");
    }
    return full;
  }

  async put(bucket: string, key: string, body: Buffer | Uint8Array) {
    const full = this.resolve(bucket, key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, body);
  }

  async delete(bucket: string, key: string) {
    await rm(this.resolve(bucket, key), { force: true });
  }

  async exists(bucket: string, key: string) {
    try {
      await stat(this.resolve(bucket, key));
      return true;
    } catch {
      return false;
    }
  }

  signedUrl(bucket: string, key: string, ttlSeconds = env.signedUrlTtlSeconds) {
    assertSafeBucket(bucket);
    assertSafeKey(key);
    const expires = Math.floor(Date.now() / 1000) + ttlSeconds;
    const sig = signKey(bucket, key, expires);
    return `/api/files/${bucket}/${key}?exp=${expires}&sig=${sig}`;
  }

  readStream(bucket: string, key: string) {
    return createReadStream(this.resolve(bucket, key));
  }

  path(bucket: string, key: string) {
    return this.resolve(bucket, key);
  }
}

export const BUCKET = "event-photos";

export const storage = new LocalStorage(env.storageRoot);
